version: 2

general:
  branches:
    only:
      - master

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/pub-sub
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
